export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';

// export const CHANGE_CURRENT_ACCOUNT = 'CHANGE_CURRENT_ACCOUNT';

// export const EDIT_ACCOUNT_NAME = 'EDIT_ACCOUNT_NAME';

// export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

export const ADD_ACTIVITY = 'ADD_NEW_ACTIVITY'
// export const EDIT_ACTIVITY = 'EDIT_ACTIVITY';
// export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';